Repository eclipse-tractusx/portal-shared-components, pull requests merged in 2024-08, with the labels that each got.

#257 fix: Selected Values Not Saved or Reset to Default in SelectList Component
  CHANGELOG.md
  package.json
  src/components/basic/SelectList/index.tsx
Labels: bug

#262 fix: handleChange function causing issue while selecting values from selectList component
  CHANGELOG.md
  package.json
  src/components/basic/SelectList/index.tsx
Labels: bug, priority

#273 feat(table): support pagination in table component
  CHANGELOG.md
  package.json
  src/components/basic/Table/index.tsx
Labels: priority
